# Thanks for downloading MindControl! #
#==============================#

# If you want to use permissions with MindControl, you must set this to true #
usePermissions: false

# Change this to change the base command alias for the plugin #
command: 'mindcontrol'

# Change the style of the progress bar when players are focusing on entities #
progressBar:
  color: 'PURPLE'
  style: 'SOLID'