# Thanks for downloading MindControl! #
#==============================#

# If you want to use permissions with MindControl, you must set this to true #
usePermissions: false

# Change this to change the base command alias for the plugin #
command: 'mindcontrol'