name: MindControl
author: SnowGears
description: Control mobs with mind control!
version: 1.0.2
api-version: 1.14
main: com.snowgears.mindcontrol.MindControl
depend: [LibsDisguises, ProtocolLib]
permissions:
    mindcontrol.use:
        description: Allows player to use mind control
        default: op
    mindcontrol.immune:
        description: Allows player to be immune to being mind controlled
        default: op
